// lib/projects.ts — 5 portfolio case studies
import type { Project } from '@/types';

export const projects: Project[] = [
  {
    slug: 'zafran-kitchen',
    name: 'Zafran Kitchen',
    client: 'Zafran Kitchen',
    city: 'Dubai',
    country: 'UAE',
    flag: '🇦🇪',
    industry: 'Restaurant & F&B',
    service: 'Social Media Marketing + Influencer Campaign',
    problem: 'Low Instagram presence, empty tables on weekdays despite great food.',
    solution: [
      'Revamped Instagram & TikTok with weekly Reels content',
      'Ran micro-influencer campaign with 12 Dubai food bloggers',
      'Meta Ads targeting expats in JLT and Marina',
      'Google Business optimization for local search',
    ],
    results: [
      { label: 'Order Growth', value: '+312%' },
      { label: 'New Followers', value: '+18K' },
      { label: 'ROAS', value: '4.5x' },
      { label: 'Google Rank', value: '#1' },
    ],
    metrics: [
      { label: 'Orders Growth', value: '+312%' },
      { label: 'New Followers', value: '+18K' },
      { label: 'ROAS', value: '4.5x' },
    ],
    duration: '4 months',
    budget: 'AED 8,000/month',
    image: 'https://images.pexels.com/photos/67468/pexels-photo-67468.jpeg?auto=compress&cs=tinysrgb&w=800',
    tags: ['Social Media', 'Meta Ads', 'Influencer', 'UAE'],
  },
  {
    slug: 'alnoor-properties',
    name: 'AlNoor Properties',
    client: 'AlNoor Properties',
    city: 'Riyadh',
    country: 'Saudi Arabia',
    flag: '🇸🇦',
    industry: 'Real Estate',
    service: 'Google Ads + LinkedIn Lead Generation',
    problem: 'Zero digital presence, relying entirely on word of mouth for new project sales.',
    solution: [
      'Google Search + Display campaigns for high-intent buyers',
      'LinkedIn Sponsored Content targeting HNWIs',
      'Landing page CRO and A/B testing',
      'CRM automation for lead nurturing',
    ],
    results: [
      { label: 'Leads/Month', value: '200+' },
      { label: 'CPL Reduction', value: '-62%' },
      { label: 'ROI', value: '6x' },
      { label: 'Projects Sold', value: '3' },
    ],
    metrics: [
      { label: 'Leads / Month', value: '200+' },
      { label: 'Lower CPL', value: '-62%' },
      { label: 'ROI', value: '6x' },
    ],
    duration: '6 months',
    budget: 'SAR 25,000/month',
    image: 'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=800',
    tags: ['Google Ads', 'LinkedIn', 'Real Estate', 'KSA'],
  },
  {
    slug: 'urbanedge-store',
    name: 'UrbanEdge Store',
    client: 'UrbanEdge Store',
    city: 'Toronto',
    country: 'Canada',
    flag: '🇨🇦',
    industry: 'E-Commerce — Fashion & Lifestyle',
    service: 'Meta Ads + SEO + Email Marketing',
    problem: 'Stuck at $12K/month revenue, burning money on ineffective Facebook ads.',
    solution: [
      'Complete Meta Ads restructure with proper funnel',
      'SEO blog content strategy targeting buying keywords',
      'Klaviyo email automation — abandoned cart, welcome flows',
      'Influencer gifting program for organic reach',
    ],
    results: [
      { label: 'Monthly Revenue', value: '$58K' },
      { label: 'Revenue Growth', value: '+383%' },
      { label: 'ROAS', value: '5.2x' },
      { label: 'Email Revenue', value: '28%' },
    ],
    metrics: [
      { label: 'Monthly Revenue', value: '$58K' },
      { label: 'Revenue Growth', value: '+383%' },
      { label: 'ROAS', value: '5.2x' },
    ],
    duration: '5 months',
    budget: 'CAD 8,000/month',
    image: 'https://images.pexels.com/photos/5632398/pexels-photo-5632398.jpeg?auto=compress&cs=tinysrgb&w=800',
    tags: ['Meta Ads', 'SEO', 'Email', 'E-Commerce'],
  },
  {
    slug: 'clearskin-clinic',
    name: 'ClearSkin Clinic',
    client: 'ClearSkin Clinic',
    city: 'Kuwait City',
    country: 'Kuwait',
    flag: '🇰🇼',
    industry: 'Medical Aesthetics',
    service: 'Instagram Marketing + Google Ads + Reputation Management',
    problem: 'Negative reviews hurting bookings despite excellent dermatology services.',
    solution: [
      'Instagram content strategy — before/after Reels, educational posts',
      'Google Ads for high-intent searches like "best dermatologist Kuwait"',
      'Reputation management — review response + generation strategy',
      'WhatsApp booking automation saving 15 hours/week',
    ],
    results: [
      { label: 'Appointments', value: '+245%' },
      { label: 'Google Rating', value: '3.2→4.8★' },
      { label: 'Followers', value: '+9K' },
      { label: 'Hours Saved', value: '15/wk' },
    ],
    metrics: [
      { label: 'Appointments', value: '+245%' },
      { label: 'Google Rating', value: '4.8★' },
      { label: 'New Followers', value: '+9K' },
    ],
    duration: '5 months',
    budget: 'KWD 1,200/month',
    image: 'https://images.pexels.com/photos/263402/pexels-photo-263402.jpeg?auto=compress&cs=tinysrgb&w=800',
    tags: ['Instagram', 'Google Ads', 'Healthcare', 'Kuwait'],
  },
  {
    slug: 'peakdrive-autos',
    name: 'PeakDrive Autos',
    client: 'PeakDrive Autos',
    city: 'Doha',
    country: 'Qatar',
    flag: '🇶🇦',
    industry: 'Automotive — Luxury Car Showroom',
    service: 'AI WhatsApp Automation + Social Media + Google Business',
    problem: 'High walk-in sales but zero digital presence and leads leaking through WhatsApp.',
    solution: [
      'Instagram + YouTube Shorts setup and content strategy',
      'AI-powered WhatsApp agent for 24/7 lead qualification',
      'Google Business optimization for local map ranking',
      'Video content production direction for showroom tours',
    ],
    results: [
      { label: 'WhatsApp Leads', value: '180+/mo' },
      { label: 'IG Followers', value: '+22K' },
      { label: 'Walk-ins', value: '3x' },
      { label: 'Maps Rank', value: '#1 Doha' },
    ],
    metrics: [
      { label: 'Leads / Month', value: '180+' },
      { label: 'IG Followers', value: '+22K' },
      { label: 'Walk-in Growth', value: '3x' },
    ],
    duration: '3 months ongoing',
    budget: 'QAR 15,000/month',
    image: 'https://images.pexels.com/photos/1545743/pexels-photo-1545743.jpeg?auto=compress&cs=tinysrgb&w=800',
    tags: ['AI Automation', 'WhatsApp', 'Automotive', 'Qatar'],
  },
  {
    slug: 'al-haya-cleaning',
    name: 'Al Haya Cleaning Services',
    client: 'Al Haya Cleaning Services',
    city: 'Dubai',
    country: 'UAE',
    flag: '🇦🇪',
    industry: 'Professional Cleaning Services',
    service: 'Web Development + SEO + Google Business Optimization',
    problem: 'Al Haya Cleaning Services needed a strong digital presence to stand out in the competitive UAE cleaning market. We built them a high-converting website, optimized their Google visibility across all 7 Emirates, and set up an instant WhatsApp booking system — turning online visitors into paying customers.',
    solution: [
      'Built a fully responsive, SEO-optimized website showcasing all services with dedicated pages for villa, apartment, and deep cleaning',
      'Targeted high-intent keywords like "villa deep cleaning Dubai" and "move-out cleaning UAE" to drive organic traffic',
      'Set up and optimized Google Business Profiles across all 7 Emirates for maximum local visibility',
      'Integrated a WhatsApp-based instant booking system for seamless customer communication and faster conversions',
    ],
    results: [
      { label: 'Online Bookings', value: '+480%' },
      { label: 'Google Rating', value: '4.9★' },
      { label: 'Reviews', value: '500+' },
      { label: 'Coverage', value: '7 Emirates' },
    ],
    metrics: [
      { label: 'Online Bookings', value: '+480%' },
      { label: 'Google Rating', value: '4.9★' },
      { label: 'Reviews', value: '500+' },
    ],
    duration: '3 months',
    budget: 'AED 6,000/month',
    image: 'https://images.pexels.com/photos/4239091/pexels-photo-4239091.jpeg?auto=compress&cs=tinysrgb&w=800',
    tags: ['Web Development', 'SEO', 'Google Business', 'UAE'],
  },
];
