// lib/services.ts — 6 agency services
import type { Service } from '@/types';

export const services: Service[] = [
  {
    slug: 'social-media-marketing',
    title: 'Social Media Marketing',
    shortDesc: 'Build a powerful brand presence across Instagram, TikTok, LinkedIn and more.',
    fullDesc: 'We create scroll-stopping content that drives engagement, followers, and most importantly — revenue. Our data-driven social media strategies are tailored to your industry, audience, and goals. From content calendars to community management, we handle it all.',
    features: [
      'Content strategy & calendar planning',
      'Reels, Stories, and carousel creation',
      'Community management & engagement',
      'Monthly analytics & performance reports',
    ],
    image: 'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=800',
    slideThemeLight: '#F0EBE0',
    slideThemeDark: '#1A1A1A',
    keywords: ['Instagram', 'TikTok', 'LinkedIn', 'Social Media', 'Content Marketing'],
  },
  {
    slug: 'ai-automation',
    title: 'AI Automation',
    shortDesc: 'Automate repetitive tasks and scale your operations with AI-powered solutions.',
    fullDesc: 'From WhatsApp AI agents that qualify leads 24/7 to automated email sequences and CRM workflows — we help you work smarter, not harder. Our AI solutions save businesses 20+ hours per week while improving response times and conversion rates.',
    features: [
      'AI WhatsApp chatbots for lead qualification',
      'CRM automation & pipeline management',
      'Email sequence automation',
      'Custom AI workflow integration',
    ],
    image: 'https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?auto=compress&cs=tinysrgb&w=800',
    slideThemeLight: '#E8F4FD',
    slideThemeDark: '#0D1B2A',
    keywords: ['AI', 'Automation', 'WhatsApp', 'Chatbot', 'CRM'],
  },
  {
    slug: 'web-development',
    title: 'Web Development',
    shortDesc: 'High-performance websites that convert visitors into paying customers.',
    fullDesc: 'We design and develop blazing-fast, SEO-optimized websites that look stunning on every device. From landing pages to complex web applications, our development team delivers pixel-perfect results with clean code and exceptional user experience.',
    features: [
      'Custom website design & development',
      'E-commerce stores (Shopify, WooCommerce)',
      'Landing pages optimized for conversions',
      'Performance optimization & Core Web Vitals',
    ],
    image: 'https://images.pexels.com/photos/1181472/pexels-photo-1181472.jpeg?auto=compress&cs=tinysrgb&w=800',
    slideThemeLight: '#F5F2ED',
    slideThemeDark: '#111111',
    keywords: ['Website', 'Development', 'E-Commerce', 'Landing Page', 'Next.js'],
  },
  {
    slug: 'google-ads',
    title: 'Google Ads Management',
    shortDesc: 'Capture high-intent buyers actively searching for your products or services.',
    fullDesc: 'Our certified Google Ads specialists create and manage campaigns that deliver measurable ROI. From Search and Display to Shopping and Performance Max, we optimize every dollar for maximum return with detailed reporting and continuous improvement.',
    features: [
      'Search, Display, and Shopping campaigns',
      'Keyword research & competitor analysis',
      'Ad copy writing & A/B testing',
      'Conversion tracking & ROI reporting',
    ],
    image: 'https://images.pexels.com/photos/590020/pexels-photo-590020.jpeg?auto=compress&cs=tinysrgb&w=800',
    slideThemeLight: '#FFF3E0',
    slideThemeDark: '#1B1208',
    keywords: ['Google Ads', 'PPC', 'SEM', 'Search Ads', 'Performance Max'],
  },
  {
    slug: 'brand-strategy',
    title: 'Brand Strategy',
    shortDesc: 'Build a memorable brand identity that stands out in a crowded market.',
    fullDesc: 'We help you define, design, and deploy a brand identity that resonates with your target audience. From logo design and brand guidelines to positioning and messaging — we create brands that people remember and trust.',
    features: [
      'Brand identity & logo design',
      'Brand guidelines & style guide',
      'Market positioning & messaging',
      'Competitor analysis & differentiation',
    ],
    image: 'https://images.pexels.com/photos/196644/pexels-photo-196644.jpeg?auto=compress&cs=tinysrgb&w=800',
    slideThemeLight: '#FCE4EC',
    slideThemeDark: '#2A0D15',
    keywords: ['Branding', 'Logo', 'Identity', 'Strategy', 'Design'],
  },
  {
    slug: 'content-creation',
    title: 'Content Creation',
    shortDesc: 'Professional photography, videography, and copywriting that tells your story.',
    fullDesc: 'Great content is the foundation of every successful marketing campaign. Our creative team produces professional photography, video production, graphic design, and copywriting that captures attention and drives action.',
    features: [
      'Professional photography & videography',
      'Graphic design & infographics',
      'Copywriting & blog content',
      'Video editing & motion graphics',
    ],
    image: 'https://images.pexels.com/photos/3379934/pexels-photo-3379934.jpeg?auto=compress&cs=tinysrgb&w=800',
    slideThemeLight: '#F3E5F5',
    slideThemeDark: '#1A0D2A',
    keywords: ['Content', 'Photography', 'Video', 'Copywriting', 'Design'],
  },
];
